config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'say/hello'=>'say#hello'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do

    get 'weather/index'

    root 'weather#index'


    get '/forecast/index', controller: 'forecast', action: 'index'

    get '/showforecast/index',controller: 'showforecast', action: 'index'
    post '/showforecast/index', controller: 'showforecast', action:'new'


  end

  #get 'weather/index', controller: Forecast
  #post '/weather/index', controller: 'index', action: 'new'
  #get 'weather/index', controller: 'weather', action: 'index'
  #post 'weather/index', controller: 'index', action: 'create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/showforecast.rb
require 'httparty'

class Showforecast

    include HTTParty

    #base_uri "http://api.openweathermap.org/data/2.5/forecast?q=Minsk,BY&mode=jsn&appid=4122e656dc75ed86c90dde6ba95fbcd1"
    base_uri "http://api.openweathermap.org/data/2.5/forecast?q="
    format :json



    # call the  api with HTTParty and parse the JSON response
    def self.call(city,country)
      response = HTTParty.get(base_uri + city + ',' + country + '&mode=jsn&appid=4122e656dc75ed86c90dde6ba95fbcd1&units=metric')
      body = JSON.parse(response.body)
      @list = body["list"]
      return @list
    end



def self.make_hash list, value, keyname1,keyname2,keyname3
  hash = Hash.new
  list.each do |l|
    temp = l["main"][value]

    dtt = l["dt_txt"]
    dt = DateTime.parse(dtt)
    tomorrow = DateTime.tomorrow.at_noon

    if dt == tomorrow
    then
      hash[keyname1] = temp.to_f
    end

    if dt == tomorrow+86400
    then
      hash[keyname2] = temp.to_f
    end

    if dt == tomorrow+172800
    then
      hash[keyname3] = temp.to_f
    end

  end
return hash
end

    def self.make_weathdescr_hash list, value, keyname1,keyname2,keyname3
      hash = Hash.new
      list.each do |l|
        temp = l["weather"][0][value]

        dtt = l["dt_txt"]
        dt = DateTime.parse(dtt)
        tomorrow = DateTime.tomorrow.at_noon

        if dt == tomorrow
        then
          hash[keyname1] = temp.to_s
        end

        if dt == tomorrow+86400
        then
          hash[keyname2] = temp.to_s
        end

        if dt == tomorrow+172800
        then
          hash[keyname3] = temp.to_s
        end

      end
      return hash
    end

    def self.make_clouds_hash list, keyname1,keyname2,keyname3
      hash = Hash.new
      list.each do |l|
        temp = l["clouds"]["all"]

        dtt = l["dt_txt"]
        dt = DateTime.parse(dtt)
        tomorrow = DateTime.tomorrow.at_noon

        if dt == tomorrow
        then
          hash[keyname1] = temp.to_s
        end

        if dt == tomorrow+86400
        then
          hash[keyname2] = temp.to_s
        end

        if dt == tomorrow+172800
        then
          hash[keyname3] = temp.to_s
        end

      end
      return hash
    end

    def self.make_wind_hash list, keyname1,keyname2,keyname3
      hash = Hash.new
      list.each do |l|
        temp = l["wind"]["speed"]

        dtt = l["dt_txt"]
        dt = DateTime.parse(dtt)
        tomorrow = DateTime.tomorrow.at_noon

        if dt == tomorrow
        then
          hash[keyname1] = temp.to_s
        end

        if dt == tomorrow+86400
        then
          hash[keyname2] = temp.to_s
        end

        if dt == tomorrow+172800
        then
          hash[keyname3] = temp.to_s
        end

      end
      return hash
    end

end

app/models/weather.rb
require 'httparty'

class Weather

  include HTTParty

  base_uri "http://api.openweathermap.org/data/2.5/group?appid=4122e656dc75ed86c90dde6ba95fbcd1&units=metric"
  format :json

  #call the api with HTTParty and parse the JSON response
  def self.call list_ids
    response = HTTParty.get(base_uri + '&id=' + list_ids)
    body = JSON.parse(response.body)
    list = body["list"]
  end

  #create a hash to store city : temp values
  def self.make_hash list, value
    hash = Hash.new
    list.each do |l|
      temp = l["main"][value]
      city = l["name"]
      hash[city] = temp
    end
    return hash
  end

  #create hash with city: cloud cover
  def self.cloud_hash list
    hash = Hash.new
    list.each do |l|
      cloud = l["clouds"]["all"]
      city = l["name"]
      hash[city] = cloud
    end
    return hash
  end

  #returns the highest value from a hash
  def self.max_value hash
    hash.max_by{|k,v| v}
  end

  #returns the lowest value from a hash
  def self.min_value hash
    hash.min_by{ |k,v| v}
  end

  #looks at the city name strings in the best weather group
  #an array of hashes
  def self.compare_city list
    city_names = Array.new
    list.each do |l|
      #gets the zeroth element of the array
      #extracts the city names
      names = l[0]
      city_names.push(names)
    end
    #return most occuring city name in group
    #need to add an exception here to check for no re-occuring values
    return city_names.group_by(&:to_s).values.max_by(&:size).try(:first)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  private
   def set_locale
     I18n.locale = params[:locale] || I18n.default_locale
   end

  def default_url_options(options = {})
    {locale: I18n.locale }.merge options
  end
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController

  def index

  end



  def new

  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello

  end
end

app/controllers/showforecast_controller.rb
class ShowforecastController < ApplicationController
  def new
    #get from UI
    @showforecast = Showforecast.new
    @showforecast = params[:showforecast]
    @city = @showforecast['cityname']
    @country = @showforecast['countryname']

    #get from BE
      #body resp from API call
    @list = Showforecast.call(@city,@country)
      #get values of temperature,humidity
    @noontempforecast = Showforecast.make_hash(@list,'temp','noontemp1',
                                               'noontemp2','noontemp3')
    @noonhumidity = Showforecast.make_hash(@list,'humidity','humidity1',
                                           'humidity2','humidity3')
      #get values of weather description
    @noonweathdescr = Showforecast.make_weathdescr_hash(@list,'description','weathdescr1',
                                                        'weathdescr2','weathdescr3')
      #get values of clouds,wind description
    @noonclouds = Showforecast.make_clouds_hash(@list,'clouds1','clouds2','clouds3')
    @noonwind = Showforecast.make_wind_hash(@list,'wind1','wind2','wind3')

    #set to UI
    @tomorrownoon = Date.tomorrow.at_noon.strftime("%d/%m/%Y %H:%M")
    @aftertomorrownoon = DateTime.tomorrow.at_noon.plus_with_duration(86400).strftime("%d/%m/%Y %H:%M")
    @afteraftertomorrownoon = DateTime.tomorrow.at_noon.plus_with_duration(172800).strftime("%d/%m/%Y %H:%M")
    render 'showforecast/index'
    end


  def index
    #get from ui
    #@cityname = params[:showforecast][:cityname]
    #@countryname = params[:showforecast][:countryname]
    #render 'showforecast/index'

    #v2
    #@showforecast = params[:showforecast][:cityname]
    #@city=params[:showforecast][:cityname]
    #@country=params[:showforecast][:countryname]


    #@city = params[:showforecast][:cityname]

  end

  def create
    showforecast = Showforecast.new(showforecast_params)
    showforecast_params
  end

private
  def showforecast_params
    params.require(:showforecast).permit(:cityname,:countryname)
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  def index

        @cities = "524901,498817,551487,1486209,491422,1496747,2013348"
        @lookup = Weather.call(@cities)
        @temp = Weather.max_value(Weather.make_hash(@lookup, "temp"))
        @pressure = Weather.max_value(Weather.make_hash(@lookup, "pressure"))
        @humidity = Weather.min_value(Weather.make_hash(@lookup, "humidity"))
        @clouds = Weather.min_value(Weather.cloud_hash(@lookup))
        @best = [@temp,  @humidity, @clouds]
        @recommend = Weather.compare_city(@best)

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecast_helper.rb
module ForecastHelper
end

app/helpers/get_data_helper.rb
module GetDataHelper
end

app/helpers/prog_helper.rb
module ProgHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/showforecast_helper.rb
module ShowforecastHelper
end

app/helpers/weather_by_ip_controller_helper.rb
module WeatherByIpControllerHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/forecast/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather App</title>
  <%= stylesheet_link_tag "style" %>

  <%= javascript_include_tag "script" %>
  <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
</head>

<body>
<div class="wrapper">
  <li class="nav"><%= " active" if I18n.locale == :ru %> <%= link_to "Rus",{locale: :ru }%> </li>
  <li class="nav"><%= " active" if I18n.locale == :en %> <%= link_to "En",{locale: :en }%> </li>

<div class="header">
  <div class="text-container">
    <h1 class="title"><%= t("wf.title")%> </h1>
    <a class="arrow" href="#section2"><span></span>&#9660;</a>
  </div>
</div>
<br>

<div class="content">
<div><button id="forecastbtn" class="forecastbtn"><a class="forecastbtn" href="/weather/index.html"><%= t("wf.btnback") %> </a></button>
</div>

<h1><%= t("wf.title")%> </h1>


<%= form_for(:showforecast, url: showforecast_index_path) do |f|%>
    <%= f.label(:cityname, "Enter city name:") %>
    <%= f.text_field(:cityname, :required => true) %>
    <%= f.label(:countryname, "Enter country code (two letters):") %>
    <%= f.text_field(:countryname, :required => true) %>
    <%= f.submit 'Submit' %>
    <% end %>


</div><h1></h1><h1></h1><h1></h1><br><br><br><br><br><br>
<div class="footer">
  <div class="footertxt">Weather app</div>
</div>
</div>
</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/hello.html.erb
<h1>Hello world! Welcome to Ruby Rails Project!</h1>
Current Day and Time is:
<%= Time.now()%>

app/views/showforecast/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather App</title>
  <%= stylesheet_link_tag "style" %>

  <%= javascript_include_tag "script" %>
  <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
</head>

<body>
<div class="wrapper">
  <!--
  <li class="nav"><%= " active" if I18n.locale == :ru %> <%= link_to "Rus",{locale: :ru }%> </li>
  <li class="nav"><%= " active" if I18n.locale == :en %> <%= link_to "En",{locale: :en }%> </li> -->

<div class="header">
  <div class="text-container">
    <h1 class="title"><%= t("wf.title")%> </h1>
    <a class="arrow" href="#section2"><span></span>&#9660;</a>
  </div>
</div>
<br>
  <div class="content">
<div><button id="forecastbtn" class="forecastbtn"><a class="forecastbtn" href="/weather/index.html"><%= t("wf.btnback") %> </a></button>
</div>
<br>
<h1><%= t("wf.header") %>
<%= @city %>,
<%= @country %>:
</h1>


<div id="wrap">
  <div class="block"><h3>Tomorrow</h3>

<div>
  <h3><%= @tomorrownoon %></h3>
  </div>
  <div>
    Temperature,°C: <%=  @noontempforecast.values[0] %>
  </div>
  <div>
    Humidity, %: <%=  @noonhumidity.values[0] %>
  </div>
  <div>
    Description: <%= @noonweathdescr.values[0] %>
  </div>
  <div>
    Clouds coverage, %: <%= @noonclouds.values[0] %>
  </div>
  <div>
    Wind speed, m/s: <%= @noonwind.values[0] %>
  </div><br>
</div>

<div class="block"><h3>After tomorrow</h3>

  <div>
    <h3><%= @aftertomorrownoon %></h3>
  </div>

  <div>
    Temperature,°C: <%=  @noontempforecast.values[1] %>
  </div>
  <div>
    Humidity, %: <%=  @noonhumidity.values[1] %>
  </div>
  <div>
    Description: <%= @noonweathdescr.values[1] %>
  </div>
  <div>
    Clouds coverage, %: <%= @noonclouds.values[1] %>
  </div>
  <div>
    Wind speed, m/s: <%= @noonwind.values[1] %>
  </div><br>
</div>

<div class="block"><h3>After after tomorrow</h3>
  <div>
  <h3><%= @afteraftertomorrownoon %></h3>
  </div>

  <div>
    Temperature,°C: <%=  @noontempforecast.values[2] %>
  </div>
  <div>
    Humidity, %: <%=  @noonhumidity.values[2] %>
  </div>
  <div>
    Description: <%= @noonweathdescr.values[2] %>
  </div>
  <div>
    Clouds coverage, %: <%= @noonclouds.values[2] %>
  </div>
  <div>
    Wind speed, m/s: <%= @noonwind.values[2] %>
  </div><br>
  </div>
</div>

  </div>

  <div class="footer">
    <div class="footertxt">Weather app</div>
  </div>

</div>
</body>
</html>

app/views/weather/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather App</title>
  <%= stylesheet_link_tag "style" %>

  <%= javascript_include_tag "script" %>
  <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
</head>

<div>
<div class="wrapper">
  <li class="nav"><%= " active" if I18n.locale == :ru %> <%= link_to "Rus",{locale: :ru }%> </li>
  <li class="nav"><%= " active" if I18n.locale == :en %> <%= link_to "En",{locale: :en }%> </li>


  <div class="header">
    <div class="text-container">
      <h1 class="title"><%= t("main.title") %>  </h1>
      <a class="arrow" href="#section2"><span></span>&#9660;</a>
    </div>
  </div>

<div class="content">
  <h5><%= t("main.time") %> <%= Time.now().strftime("%d/%m/%Y %H:%M")%></h5>


  <button id="forecastbtn" class="forecastbtn"><a class="forecastbtn" href="/forecast/index.html"><%= t("main.btn") %> </a></button>
  </div>


  <h1><%= t("main.header") %> </h1>
  <h3><%= t("main.entercity") %> </h3>
  <span id="error"></span>
  <div>
  <input size="25" type="text" name="city" id="city" class="city" required><br><br>

  <div> <%= t("main.slidetoday")%> <input type="range" id="slider" min="1" max="2" value="1"> <%= t("main.slidetom")%></div><br>
    <button id="submitWeather" class="submitWeather"><%= t("main.searchbtn")%> </button><br>
  </div><br>
  <div id="output" hidden> </div>
  <br>
  <div id="show"></div>

  <br>
  <h1><%= t("main.top")%>  </h1>
  <table class="CitiesTable">
    <tr>
    <th><%= t("main.tblcityname")%></th>
    <th><%= t("main.tblpressure")%></th>
    <th><%= t("main.tbltemp")%></th>
    <th><%= t("main.tblhum")%></th>
    <th><%= t("main.tblcloud")%></th>
    <th><%= t("main.tblwindspd")%></th>
    <th><%= t("main.tblwinddir")%></th>
    <th><%= t("main.tblwdescr")%></th>
  </tr>

  <% @lookup.each do |l| %>
      <tr>
        <td><%= l["name"] %></td>
        <td><%= l["main"]["pressure"] * 0.75 %></td> <!--transfer from hPA to mmHg-->
        <td><%= l["main"]["temp"] %></td>
        <td><%= l["main"]["humidity"] %></td>
        <td><%= l["clouds"]["all"] %></td>
        <td><%= l["wind"]["speed"] %></td>
        <td><%= l["wind"]["deg"] %></td>
        <td><%= l["weather"][0]["main"] %></td>
      </tr>
  <% end %>
  </table>

  <h2><%= t("main.nice")%>   </h2>
  <table>
  <tr class="BestWeatherTable">
    <tr>
      <th><%= t("main.nicehot")%></th>

      <th><%= t("main.nicehum")%> </th>
      <th><%= t("main.nicecloud")%></th>

    </tr>

  <tr>
  <% @best.each do |b| %>

        <td><%= b[0] %>,
        <%= b[1] %></td>


  <% end %>
  </tr>

  </table>
  <br><br><br><br>

<%= javascript_include_tag "wip" 'data-turbolinks-track' => true %>


</div>

<div class="footer">
  <div class="footertxt">Weather app</div>
</div>

</div>
</body>
</html>